bvgs_app/apps/events/urls.py
from django.conf.urls import patterns, include, url

from . import views

urlpatterns = patterns('',
    url(
        r'^$',
        view=views.EventListView.as_view(),
        name='events',
    ),
    url(
        r'^(?P<pk>\d+)/$',
        view=views.EventDetailView.as_view(),
        name='event_detail',
    ),
)

bvgs_app/apps/players/urls.py
from django.conf.urls import patterns, include, url

from . import views

urlpatterns = patterns('',
    url(
    	r'^$',
    	view=views.PlayerListView.as_view(),
    	name='players',
	),
    url(
        r'^(?P<pk>\d+)/$',
        view=views.PlayerDetailView.as_view(),
        name='player_detail',
    ),
)

bvgs_app/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    url(r'^players/', include('bvgs_app.apps.players.urls')),
    url(r'^events/', include('bvgs_app.apps.events.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

bvgs_app/apps/events/models.py
from django.db import models


class Event(models.Model):

    name = models.CharField(max_length=120)
    starts = models.DateTimeField()
    ends = models.DateTimeField()
    capacity = models.PositiveIntegerField()
    attendees = models.ManyToManyField('players.Player', through="EventPlayer")
    last_event = models.ForeignKey('self', blank=True, null=True)

    def __str__(self):
        return self.name


class EventPlayer(models.Model):

    event = models.ForeignKey(Event)
    player = models.ForeignKey('players.Player')
    exp_given = models.BooleanField(default=False)

    class Meta:
        unique_together = ('event', 'player')

    def _increase_multiplier(self):
        if self.event.last_event is not None:
            if self.player in self.event.last_event.attendees.all():
                self.player.increase_multiplier_consecutive()
            else:
                self.player.increase_multiplier()
        else:
            self.player.increase_multiplier()

    def save(self, *args, **kargs):
        if self.id is None:
            self.player.attend_event()
            self._increase_multiplier()
            self.exp_given = True
            self.player.save()
        super(EventPlayer, self).save(*args, **kargs)

bvgs_app/apps/players/models.py
import decimal

from django.db import models

from .managers import PlayerManager, BASE_EXP_AMOUNT


MULT_INCREASE = decimal.Decimal(1.1)
MULT_CONSECUTIVE = decimal.Decimal(1.12)


class Player(models.Model):

    '''Model defining a BVGS member and their stats'''

    name = models.CharField(max_length=120)
    level = models.PositiveIntegerField(default=0)
    exp = models.PositiveIntegerField(default=0)
    multiplier = models.DecimalField(decimal_places=2, max_digits=10, default=1.0)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    objects = PlayerManager()

    def attend_event(self):
        self.exp += self.next_exp_amount

    def increase_multiplier(self):
        self.multiplier = round(self.multiplier * MULT_INCREASE, 2)

    def increase_multiplier_consecutive(self):
        self.multiplier = round(self.multiplier * MULT_CONSECUTIVE, 2)

    def calculate_level(self):
        for level, exp in enumerate(Player.objects.exp_table):
            self.req_exp = exp - self.exp
            if exp > self.exp:
                self.level = level
                break
        return self.level

    @property
    def next_exp_amount(self):
        if self.exp:
            return int(BASE_EXP_AMOUNT * (self.multiplier * MULT_INCREASE))
        else:
            return BASE_EXP_AMOUNT * self.multiplier

    def __str__(self):
        return self.name

    def save(self, *args, **kargs):
        self.calculate_level()
        super(Player, self).save(*args, **kargs)

    class Meta:
        ordering = ['-level', 'name']

bvgs_app/apps/events/forms.py
from django import forms
from .models import Event


class EventForm(forms.ModelForm):

    class Meta:
        model = Event
        fields = ['name', 'starts', 'ends', 'last_event', 'capacity', 'attendees']

bvgs_app/apps/players/forms.py
from django import forms
from .models import Player


class PlayerForm(forms.ModelForm):
    class Meta:
        model = Player
        fields = ['name']

bvgs_app/apps/events/views.py
from django.views import generic
from django.http import HttpResponse

from .models import Event
from .forms import EventForm


class EventListView(generic.ListView):
    model = Event


class EventDetailView(generic.DetailView):
    model = Event


class EventCreateView(generic.CreateView):
    model = Event
    form = EventForm


class EventUpdateView(generic.UpdateView):
    model = Event
    form = EventForm

bvgs_app/apps/players/views.py
# Create your views here.
from django.views import generic
from django.http import HttpResponse

from .models import Player
from .forms import PlayerForm


class PlayerListView(generic.ListView):
    model = Player


class PlayerDetailView(generic.DetailView):
    model = Player


class PlayerCreateView(generic.CreateView):
    model = Player
    form = PlayerForm


class PlayerUpdateView(generic.UpdateView):
    model = Player
    form = PlayerForm

templates/base.html
{% load compress %}
{% load staticfiles %}

<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>{% block page_title %}BVGS{% endblock %}</title>
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

  {% block meta %}
  {% endblock %}

  {# use the CDN to get bootstrap css. can not be inside compress css block #}
  {% block cdn_css %}
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.2/css/bootstrap.min.css">
  {% endblock cdn_css %}

  {% compress css %}
  {% block css %}{% endblock %}
  {% endcompress %}
  {% compress js %}
  {% endcompress %}
</head>
<body class="{% block body_class %}{% endblock %}" {% block body_attributes %}{% endblock %}>
{% block body %}
  <header>
    {% block header %}{% endblock %}
  </header>

  <div role="main">
    {% block content %}{% endblock %}
  </div>

  <footer>
    {% block footer %}
    <div class="container">
      <hr>
    </div>
    {% endblock footer %}
  </footer>


  <!-- JavaScript at the bottom for fast page loading -->

  <!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline -->
  {% block cdn_js %}
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.2/js/bootstrap.min.js"></script>
  {% endblock cdn_js %}

  <!-- scripts concatenated and minified via django-compressor -->
  {% compress js %}
  {% block js %}
  {% endblock js %}
  {% endcompress %}
  <!-- end scripts -->

  {% endblock %}
</body>
</html>

templates/events/event_detail.html
{% extends "base.html" %}

{% block content %}
<h1>{{ object.name }}</h1>
<p>{{ object.starts}} - {{ object.ends }}</p>
<p>Attendees: ({{ object.attendees.count }})
<ul>
{% for player in object.attendees.all %}
<li><a href="{% url 'player_detail' player.id %}">{{ player }}</a></li>
{% endfor %}
</ul>
</p>
{% endblock %}

templates/events/event_list.html
{% extends "base.html" %}

{% block content %}
<ul>
{% for event in object_list %}
    <li><a href="{% url 'event_detail' event.id %}">{{ event }}</a></li>
{% endfor %}
</ul>
{% endblock %}

templates/players/player_detail.html
{% extends "base.html" %}

{% block content %}
<h1>{{ object.name }}</h1>
<h2>Level {{ object.level }}</h2>
<h3>{{ object.exp }} XP</h3>
<p>Attended:
<ul>
{% for event in object.event_set.all %}
<li><a href="{% url 'event_detail' event.id %}">{{ event }}</a></li>
{% endfor %}
</ul>
</p>
{% endblock %}

templates/players/player_list.html
{% extends "base.html" %}

{% block content %}
<ul>
{% for player in object_list %}
    <li>{{ player }}</li>
{% endfor %}
</ul>
{% endblock %}